### ISSUE TITLE
Doesn't seem to do anything

### ISSUE THREAD

**Issue by Slapbox** [codastic/react-positioning-portal#19]
Hey Codastic team!

I came across this package and gave it a try, but it doesn't seem to have any affect on the DOM. It doesn't seem to be creating a portal, or using one I pass in if I use the `rootNode` prop.

I tried making my `portalContent` a function and logging `relatedWidth` each time it executes, but it apparently never executes. Any ideas? Thanks for sharing!

**Comment by webholics** [comment]
Hi, I'm happy to support. Could you share a code snippet?
Otherwise you could have a look at the storybook in this repo. There are some examples.

**Comment by Slapbox** [comment]
Hey @webholics thanks for your reply!

 I ended up going another route, but the code was adapted from the Storybooks and was nearly identical so I'm not sure what the issue I hit might have been. Feel free to close this issue if you think it appropriate and thanks again.
