### ISSUE TITLE
Add relatedHeight to PortalContentRenderProps

### ISSUE THREAD

**Issue by BraunreutherA** [codastic/react-positioning-portal#23]
Hey there, 

would it be okay to add `relatedHeight` (the parent height) as a property to the `portalContent` render function? 

If yes, I here is the [PR](https://github.com/codastic/react-positioning-portal/pull/24) for this. 

Best 

Alex

**Comment by webholics** [comment]
Hi Alex, 

I think that makes sense and saw you already created a pull request. Will have a look. Thank you.
